version: "3"

services:

  virkrdb:
    image: postgres:alpine
    volumes:
      - ./backend/src/main/sql/ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    expose:
      - "5432"

  virkr:
    image: tomcat:7-jre7
    ports:
      - "8080:8080"
    volumes:
      - ./backend/build/libs/virkr-0.0.1.war:/usr/local/tomcat/webapps/virkr.war
    environment:
      - SPRING_PROFILES_ACTIVE=ERST
      - VIRKR_MAPS_APIKEY==AIzaSyCFIFw8X7OTSOJ5lh-Z-HUxzNzbD2TYl-w
      - VIRKR_CVR_PASSWORD=aa2d9502-86b1-4b08-b874-fd10960df469
    links:
      - virkrdb
