server:
  port: 9092

virkr:
  aarsrapporter:
    url: http://distribution.virk.dk/offentliggoerelser/_search
  cvr:
    url: http://distribution.virk.dk/cvr-permanent/_search
    deltagerurl: http://distribution.virk.dk/cvr-permanent/deltager
    username: Søren_Hartvig_CVR_I_SKYEN
    password: PASSWD_TIL_SKYEN
  maps:
    url: https://maps.googleapis.com/maps/api/geocode/json
    apikey: APIKEY_TIL_GOOGLE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
