server:
  port: 9092

virkr:
  aarsrapporter:
    url: http://distribution.virk.dk/offentliggoerelser/_search
  cvr:
    url: http://distribution.virk.dk/cvr-permanent/_search
    username: Søren_Hartvig_CVR_I_SKYEN
    password: aa2d9502-86b1-4b08-b874-fd10960df469
  maps:
    url: https://maps.googleapis.com/maps/api/geocode/json
    apikey: AIzaSyCFIFw8X7OTSOJ5lh-Z-HUxzNzbD2TYl-w

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
